resolver: lts-12.20
packages:
- .
- project-m36
extra-deps:
- data-accessor-transformers-0.2.1.7
- data-interval-1.2.0
- extended-reals-0.2.1.0
- gnuplot-0.5.5.3
- aeson-1.4.2.0
- distributed-process-0.7.4
- distributed-process-async-0.2.6
- distributed-process-client-server-0.2.3
- distributed-process-extras-0.3.2
- rset-1.0.0
- hashable-time-0.2.0.2
- network-transport-tcp-0.6.0
- stm-containers-1.1.0.2
- deferred-folds-0.9.9.1
- focus-1.0.1.2
- stm-hamt-1.2.0.2
- primitive-0.6.4.0
- primitive-extras-0.7.1
# - servant-swagger-ui-0.3.2.3.19.3

allow-newer: true

flags:
  project-m36:
    build-examples: true

ghc-options:
  $targets: -Wall -optl-fuse-ld=bfd
